import { StyleSheet } from "react-native";
import { colors } from "../theme";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  menuAnchor: {
    position: "absolute",
    top: 70,
    left: 12,
    zIndex: 30,
  },
  menuButton: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(37, 99, 235, 0.16)",
    borderRadius: 999,
    backgroundColor: colors.brand,
    shadowColor: "#2563eb",
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  hamburger: {
    gap: 4,
  },
  hamburgerLine: {
    width: 17,
    height: 2,
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15, 23, 42, 0.3)",
    zIndex: 31,
  },
  menuPanel: {
    position: "absolute",
    top: 115,
    left: 42,
    width: 280,
    maxWidth: "92%",
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    backgroundColor: "#f8fbff",
    shadowColor: "#0f172a",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
    opacity: 0,
    transform: [{ translateY: -10 }, { scale: 0.98 }],
    zIndex: 32,
  },
  menuPanelOpen: {
    opacity: 1,
    transform: [{ translateY: 0 }, { scale: 1 }],
  },
  menuHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  menuTitle: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  menuClose: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  menuCloseText: {
    color: colors.text,
    fontSize: 22,
    lineHeight: 22,
  },
  menuItem: {
    borderWidth: 1,
    borderColor: "transparent",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "#ffffff",
    marginBottom: 8,
  },
  menuItemActive: {
    borderColor: "#bfd4f7",
    backgroundColor: "#e5efff",
  },
  menuItemText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "600",
  },
  menuItemTextActive: {
    color: colors.brand,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 88,
    paddingBottom: 28,
  },
  title: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "800",
  },
  subtitle: {
    color: colors.textMuted,
    marginTop: 2,
    marginBottom: 12,
  },
  body: {
    marginTop: 4,
  },
});
